modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="playingcards"

version="1.15.2-1.0.3"

displayName="Playing Cards"

updateJSONURL="http://myurl.me/"

displayURL=""

logoFile=""

credits="Kryto627 for helping with some code."

authors="Calemi"

description='''
Adds playing cards, poker chips, and more!
'''