modLoader="javafml"
loaderVersion="[31,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="playingcards"
    namespace="playingcards"
    version="1.0.0"
    displayName="Playing Cards"
    authors="Calemi, Kryto627"
    description='''
    Adds playing cards, poker chips, and more!
    '''

[[dependencies.cspirit]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"